services:
  - type: web
    name: Lakshya-Saraswat-Portfolio
    runtime: node
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend
    startCommand: npm start --prefix backend
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://lakshya-saraswat-portfolio.onrender.com
      - key: MONGO_URI
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        value: lakshya3924@gmail.com
